// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5yOrTCoqql2Q_tn9nORjYn2p24xhI24I',
    appId: '1:56611133800:web:a6487dcaf01b5855129edd',
    messagingSenderId: '56611133800',
    projectId: 'moviles-b6e7f',
    authDomain: 'moviles-b6e7f.firebaseapp.com',
    storageBucket: 'moviles-b6e7f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVr33KGGvJaQBj74hspLiDxmFSFV2nOoI',
    appId: '1:56611133800:android:6666b1569ad4692a129edd',
    messagingSenderId: '56611133800',
    projectId: 'moviles-b6e7f',
    storageBucket: 'moviles-b6e7f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6VG6kR5tz8TqKTUI0SaIsjqB4TV1nx4',
    appId: '1:56611133800:ios:3de096b61de893bc129edd',
    messagingSenderId: '56611133800',
    projectId: 'moviles-b6e7f',
    storageBucket: 'moviles-b6e7f.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs6VG6kR5tz8TqKTUI0SaIsjqB4TV1nx4',
    appId: '1:56611133800:ios:3de096b61de893bc129edd',
    messagingSenderId: '56611133800',
    projectId: 'moviles-b6e7f',
    storageBucket: 'moviles-b6e7f.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5yOrTCoqql2Q_tn9nORjYn2p24xhI24I',
    appId: '1:56611133800:web:adc19971910aeefc129edd',
    messagingSenderId: '56611133800',
    projectId: 'moviles-b6e7f',
    authDomain: 'moviles-b6e7f.firebaseapp.com',
    storageBucket: 'moviles-b6e7f.appspot.com',
  );
}
